version: '3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.2
    container_name: wdip-elasticsearch
    volumes: 
      - elasticsearch:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    environment: 
      discovery.type: single-node
  kibana:
    image: docker.elastic.co/kibana/kibana:6.4.2
    container_name: wdip-kibana
    depends_on:
      - elasticsearch
    # volumes:
      # - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    ports: 
      - 5601:5601
    environment: 
      ELASTICSEARCH_URL: "http://elasticsearch:9200"
  sqs:
    image: roribio16/alpine-sqs:latest
    container_name: wdip-sqs
    volumes:
      - ./config/sqs/elasticmq.conf:/opt/config/elasticmq.conf
    ports:
      - 9324:9324
      - 9325:9325
    stdin_open: true
    tty: true
  wdip-be:
    image: amaysim/serverless:1.30.3
    container_name: wdip-be
    depends_on:
      - elasticsearch
      - sqs
    ports: 
      - 3001:3001
      - 9229:9229
    # environment: 
    #   - SLS_DEBUG=* # Enable for verbose logging from serverless
    volumes: 
      - ./wdip-be:/app
      - ./config/.aws:/root/.aws
    working_dir: /app
    command: npm run debug
  wdip-fe:
    image: node:10
    container_name: wdip-fe
    depends_on: 
      - wdip-be
    ports: 
      - 3000:3000
    volumes: 
      - ./wdip-fe:/app
    working_dir: /app
    command: npm start
  runtime-config:
    build: ./config/runtime
    container_name: wdip-runtime-config
    depends_on: 
      - kibana
    volumes: 
      - ./config/runtime/kibana:/runtime/kibana

volumes: 
  elasticsearch: