// tslint:disable
/**
 * WDIP
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.0.1
 * Contact: markus@silberstein.nu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists } from '../runtime';
/**
 * 
 * @export
 * @interface ErrorModel
 */
export interface ErrorModel {
    /**
     * 
     * @type {number}
     * @memberof ErrorModel
     */
    code: number;
    /**
     * 
     * @type {string}
     * @memberof ErrorModel
     */
    message: string;
}

export function ErrorModelFromJSON(json: any): ErrorModel {
    return {
        'code': json['code'],
        'message': json['message'],
    };
}

export function ErrorModelToJSON(value?: ErrorModel): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'code': value.code,
        'message': value.message,
    };
}


