// tslint:disable
/**
 * WDIP
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.0.1
 * Contact: markus@silberstein.nu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists } from '../runtime';
/**
 * 
 * @export
 * @interface Word
 */
export interface Word {
    /**
     * 
     * @type {string}
     * @memberof Word
     */
    text: string;
    /**
     * 
     * @type {number}
     * @memberof Word
     */
    value: number;
}

export function WordFromJSON(json: any): Word {
    return {
        'text': json['text'],
        'value': json['value'],
    };
}

export function WordToJSON(value?: Word): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'text': value.text,
        'value': value.value,
    };
}


