// tslint:disable
/**
 * WDIP
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.0.1
 * Contact: markus@silberstein.nu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    Word,
    WordFromJSON,
    WordToJSON,
} from '../models';

export interface GetWordCloudRequest {
    fromDate?: string;
    toDate?: string;
}

/**
 * no description
 */
export class ChartsApi extends runtime.BaseAPI {

    /**
     * Gets word cloud data, ie keywords and their frequency
     */
    async getWordCloudRaw(requestParameters: GetWordCloudRequest): Promise<runtime.ApiResponse<Array<Word>>> {
        const queryParameters: runtime.HTTPQuery = {};

        if (requestParameters.fromDate !== undefined) {
            queryParameters['fromDate'] = requestParameters.fromDate;
        }

        if (requestParameters.toDate !== undefined) {
            queryParameters['toDate'] = requestParameters.toDate;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/charts/wordcloud`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(WordFromJSON));
    }

    /**
     * Gets word cloud data, ie keywords and their frequency
     */
    async getWordCloud(requestParameters: GetWordCloudRequest): Promise<Array<Word>> {
        const response = await this.getWordCloudRaw(requestParameters);
        return await response.value();
    }

}
