// tslint:disable
/**
 * WDIP
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.0.1
 * Contact: markus@silberstein.nu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    MotionsByParty,
    MotionsByPartyFromJSON,
    MotionsByPartyToJSON,
    Party,
    PartyFromJSON,
    PartyToJSON,
} from '../models';

export interface GetMotionsByPartyRequest {
    fromDate?: string;
    toDate?: string;
}

/**
 * no description
 */
export class MotionsApi extends runtime.BaseAPI {

    /**
     * Get a summary of all motions by party
     */
    async getMotionsByPartyRaw(requestParameters: GetMotionsByPartyRequest): Promise<runtime.ApiResponse<MotionsByParty>> {
        const queryParameters: runtime.HTTPQuery = {};

        if (requestParameters.fromDate !== undefined) {
            queryParameters['fromDate'] = requestParameters.fromDate;
        }

        if (requestParameters.toDate !== undefined) {
            queryParameters['toDate'] = requestParameters.toDate;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/motions/byparty`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => MotionsByPartyFromJSON(jsonValue));
    }

    /**
     * Get a summary of all motions by party
     */
    async getMotionsByParty(requestParameters: GetMotionsByPartyRequest): Promise<MotionsByParty> {
        const response = await this.getMotionsByPartyRaw(requestParameters);
        return await response.value();
    }

}
