openapi: "3.0.0"
info:
  version: 0.0.1
  title: WDIP
  license:
    name: GPLv3
    url: https://www.gnu.org/licenses/gpl-3.0.en.html
  contact:
    name: Markus Silberstein Hont
    email: markus@silberstein.nu
    url: http://www.hejare.se
servers:
  - url: http://localhost:3001
paths:
  /motions/byparty:
    get:
      summary: Get a summary of all motions by party
      operationId: getMotionsByParty
      tags:
        - motions
      parameters:
        - name: fromDate
          in: query
          description: From which date (inclusive) data should be returned.
          required: false
          schema:
            type: string
            format: date
        - name: toDate
          in: query
          description: To which date (inclusive) data should be returned.
          required: false
          schema:
            type: string
            format: date
      responses:
        '200':
          description: A list of all motions by party
          content:
            application/json:    
              schema:
                $ref: "#/components/schemas/MotionsByParty"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorModel"
  /charts/wordcloud:
    get:
      summary: Gets word cloud data, ie keywords and their frequency
      operationId: getWordCloud
      tags:
        - charts
      responses:
        '200':
          description: A list of words and their number of appearances
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Words"
components:
  schemas:
    MotionsByParty:
      required:
        - fromDate
        - toDate
        - results
      properties:
        fromDate:
          type: string
          format: date
        toDate:
          type: string
          format: date
        results:
          type: array
          items:
            type: object
            properties:
              party:
                type: string
              submitted:
                type: integer
              approved:
                type: integer
              declined:
                type: integer
    Word:
      required:
        - text
        - value
      properties:
        text:
          type: string
        value:
          type: integer
    Words:
      type: array
      items:
        $ref: "#/components/schemas/Word"
    ErrorModel:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string