openapi: "3.0.0"
info:
  version: 0.0.1
  title: WDIP
  license:
    name: GPLv3
    url: https://www.gnu.org/licenses/gpl-3.0.en.html
  contact:
    name: Markus Silberstein Hont
    email: markus@silberstein.nu
    url: http://www.hejare.se
servers:
  - url: http://localhost:3001
paths:
  /motions/byparty:
    get:
      summary: Get a summary of all motions by party
      operationId: getMotionsByParty
      tags:
        - motions
      parameters:
        - name: fromDate
          in: query
          description: From which date (inclusive) data should be returned.
          required: false
          schema:
            type: string
            #format: date, see https://github.com/OpenAPITools/openapi-generator/issues/926
        - name: toDate
          in: query
          description: To which date (inclusive) data should be returned.
          required: false
          schema:
            type: string
            #format: date
      responses:
        '200':
          description: A list of all motions by party
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
          content:
            application/json:    
              schema:
                $ref: "#/components/schemas/MotionsByParty"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Partys"
  /motions/byparty/{id}:
    get:
      summary: Gets motions for the specified party and time period
      operationId: getMotionsForParty
      tags:
        - motions
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: Identifier for party
        - in: query
          name: fromDate
          description: From which date (inclusive) data should be returned.
          required: false
          schema:
            type: string
            #format: date
        - in: query
          name: toDate
          description: To which date (inclusive) data should be returned.
          required: false
          schema:
            type: string
            #format: date
        - in: query
          name: fromResultNo
          description: Where to begin the batch of results (pagination) 
          required: false
          schema:
            type: integer
      responses:
        '200':
          description: A list of motions
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Motions"
  /motions/{id}:
    get:
      summary: Gets motion for the specified id
      operationId: getMotion
      tags:
        - motions
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: Identifier for motion
      responses:
        '200':
          description: Motion
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Motion"
  /charts/wordcloud:
    get:
      summary: Gets word cloud data, ie keywords and their frequency
      operationId: getWordCloud
      tags:
        - charts
      parameters:
        - name: fromDate
          in: query
          description: From which date (inclusive) data should be returned.
          required: false
          schema:
            type: string
            #format: date
        - name: toDate
          in: query
          description: To which date (inclusive) data should be returned.
          required: false
          schema:
            type: string
            #format: date
      responses:
        '200':
          description: A list of words and their number of appearances
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Words"
  /parties:
    get:
      summary: Gets data for all the parties, i.e. GAL-TAN position and party color
      operationId: getAllParties
      tags:
        - party
      responses:
        '200':
          description: A list of the parties, their X- and Y-positions and party color. 
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Partys"
components:
  schemas:
    MotionsByParty:
      required:
        - fromDate
        - toDate
        - results
      properties:
        fromDate:
          type: string
          #format: date
        toDate:
          type: string
          #format: date
        results:
          type: array
          items:
            type: object
            properties:
              party:
                type: string
              submitted:
                type: integer
              approved:
                type: integer
              declined:
                type: integer
    Word:
      required:
        - text
        - value
      properties:
        text:
          type: string
        value:
          type: integer
    Words:
      type: array
      items:
        $ref: "#/components/schemas/Word"
    Party:
      required:
        - id
        - x
        - y
        - color
        - name
      properties:
        id:
          type: string
        x:
          type: integer
        y:
          type: integer
        color:
          type: string
        name:
          type: string
    Partys:
      type: array
      items:
        $ref: "#/components/schemas/Party"
    Proposal:
      required:
        - wording
        - committeeStatus
        - chamberStatus
      properties:
        wording:
          type: string
        committeeStatus:
          type: string
        chamberStatus:
          type: string
    Stakeholder:
      required:
        - id
        - name
        - party
      properties:
        id:
          type: string
        name:
          type: string
        party:
            $ref: "#/components/schemas/Party"
    Motion:
      required:
        - id
        - title
        - documentStatus
        - documentType
        - proposals
        - stakeholders
      properties:
        id:
          type: string
        title:
          type: string
        documentStatus:
          type: string
        documentType:
          type: string
        proposals:
          type: array
          items:
            $ref: "#/components/schemas/Proposal"
        stakeholders:
          type: array
          items:
            $ref: "#/components/schemas/Stakeholder"
    Motions:
      properties:
        results:
          type: array
          items:
            $ref: "#/components/schemas/Motion"
        total:
          type: integer
        startResult:
          type: integer
        endResult:
          type: integer
    ErrorModel:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
