/// <reference path="./custom.d.ts" />
// tslint:disable
/**
 * WDIP
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.0.1
 * Contact: markus@silberstein.nu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as url from "url";
import * as portableFetch from "portable-fetch";
import { Configuration } from "./configuration";

const BASE_PATH = "http://localhost:3001".replace(/\/+$/, "");

/**
 *
 * @export
 */
export const COLLECTION_FORMATS = {
    csv: ",",
    ssv: " ",
    tsv: "\t",
    pipes: "|",
};

/**
 *
 * @export
 * @interface FetchAPI
 */
export interface FetchAPI {
    (url: string, init?: any): Promise<Response>;
}

/**
 *  
 * @export
 * @interface FetchArgs
 */
export interface FetchArgs {
    url: string;
    options: any;
}

/**
 * 
 * @export
 * @class BaseAPI
 */
export class BaseAPI {
    protected configuration: Configuration | undefined;

    constructor(configuration?: Configuration, protected basePath: string = BASE_PATH, protected fetch: FetchAPI = portableFetch) {
        if (configuration) {
            this.configuration = configuration;
            this.basePath = configuration.basePath || this.basePath;
        }
    }
};

/**
 * 
 * @export
 * @class RequiredError
 * @extends {Error}
 */
export class RequiredError extends Error {
    name: "RequiredError" = "RequiredError";
    constructor(public field: string, msg?: string) {
        super(msg);
    }
}

/**
 * 
 * @export
 * @interface ErrorModel
 */
export interface ErrorModel {
    /**
     * 
     * @type {number}
     * @memberof ErrorModel
     */
    code: number;
    /**
     * 
     * @type {string}
     * @memberof ErrorModel
     */
    message: string;
}

/**
 * 
 * @export
 * @interface MotionsByParty
 */
export interface MotionsByParty {
    /**
     * 
     * @type {string}
     * @memberof MotionsByParty
     */
    fromDate: string;
    /**
     * 
     * @type {string}
     * @memberof MotionsByParty
     */
    toDate: string;
    /**
     * 
     * @type {Array<MotionsByPartyResults>}
     * @memberof MotionsByParty
     */
    results: Array<MotionsByPartyResults>;
}

/**
 * 
 * @export
 * @interface MotionsByPartyResults
 */
export interface MotionsByPartyResults {
    /**
     * 
     * @type {string}
     * @memberof MotionsByPartyResults
     */
    party?: string;
    /**
     * 
     * @type {number}
     * @memberof MotionsByPartyResults
     */
    submitted?: number;
    /**
     * 
     * @type {number}
     * @memberof MotionsByPartyResults
     */
    approved?: number;
    /**
     * 
     * @type {number}
     * @memberof MotionsByPartyResults
     */
    declined?: number;
}

/**
 * 
 * @export
 * @interface Word
 */
export interface Word {
    /**
     * 
     * @type {string}
     * @memberof Word
     */
    text: string;
    /**
     * 
     * @type {number}
     * @memberof Word
     */
    value: number;
}

/**
 * 
 * @export
 * @interface Words
 */
export interface Words extends Array<Word> {
}


/**
 * ChartsApi - fetch parameter creator
 * @export
 */
export const ChartsApiFetchParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Gets word cloud data, ie keywords and their frequency
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getWordCloud(options: any = {}): FetchArgs {
            const localVarPath = `/charts/wordcloud`;
            const localVarUrlObj = url.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = Object.assign({ method: 'GET' }, baseOptions, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ChartsApi - functional programming interface
 * @export
 */
export const ChartsApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Gets word cloud data, ie keywords and their frequency
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getWordCloud(options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<Words> {
            const localVarFetchArgs = ChartsApiFetchParamCreator(configuration).getWordCloud(options);
            return (fetch: FetchAPI = portableFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response.json();
                    } else {
                        throw response;
                    }
                });
            };
        },
    }
};

/**
 * ChartsApi - factory interface
 * @export
 */
export const ChartsApiFactory = function (configuration?: Configuration, fetch?: FetchAPI, basePath?: string) {
    return {
        /**
         * 
         * @summary Gets word cloud data, ie keywords and their frequency
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getWordCloud(options?: any) {
            return ChartsApiFp(configuration).getWordCloud(options)(fetch, basePath);
        },
    };
};

/**
 * ChartsApi - object-oriented interface
 * @export
 * @class ChartsApi
 * @extends {BaseAPI}
 */
export class ChartsApi extends BaseAPI {
    /**
     * 
     * @summary Gets word cloud data, ie keywords and their frequency
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ChartsApi
     */
    public getWordCloud(options?: any) {
        return ChartsApiFp(this.configuration).getWordCloud(options)(this.fetch, this.basePath);
    }

}

/**
 * MotionsApi - fetch parameter creator
 * @export
 */
export const MotionsApiFetchParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Get a summary of all motions by party
         * @param {string} [fromDate] From which date (inclusive) data should be returned.
         * @param {string} [toDate] To which date (inclusive) data should be returned.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getMotionsByParty(fromDate?: string, toDate?: string, options: any = {}): FetchArgs {
            const localVarPath = `/motions/byparty`;
            const localVarUrlObj = url.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = Object.assign({ method: 'GET' }, baseOptions, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (fromDate !== undefined) {
                localVarQueryParameter['fromDate'] = (fromDate as any).toISOString();
            }

            if (toDate !== undefined) {
                localVarQueryParameter['toDate'] = (toDate as any).toISOString();
            }

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * MotionsApi - functional programming interface
 * @export
 */
export const MotionsApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Get a summary of all motions by party
         * @param {string} [fromDate] From which date (inclusive) data should be returned.
         * @param {string} [toDate] To which date (inclusive) data should be returned.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getMotionsByParty(fromDate?: string, toDate?: string, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<MotionsByParty> {
            const localVarFetchArgs = MotionsApiFetchParamCreator(configuration).getMotionsByParty(fromDate, toDate, options);
            return (fetch: FetchAPI = portableFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response.json();
                    } else {
                        throw response;
                    }
                });
            };
        },
    }
};

/**
 * MotionsApi - factory interface
 * @export
 */
export const MotionsApiFactory = function (configuration?: Configuration, fetch?: FetchAPI, basePath?: string) {
    return {
        /**
         * 
         * @summary Get a summary of all motions by party
         * @param {string} [fromDate] From which date (inclusive) data should be returned.
         * @param {string} [toDate] To which date (inclusive) data should be returned.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getMotionsByParty(fromDate?: string, toDate?: string, options?: any) {
            return MotionsApiFp(configuration).getMotionsByParty(fromDate, toDate, options)(fetch, basePath);
        },
    };
};

/**
 * MotionsApi - object-oriented interface
 * @export
 * @class MotionsApi
 * @extends {BaseAPI}
 */
export class MotionsApi extends BaseAPI {
    /**
     * 
     * @summary Get a summary of all motions by party
     * @param {string} [fromDate] From which date (inclusive) data should be returned.
     * @param {string} [toDate] To which date (inclusive) data should be returned.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MotionsApi
     */
    public getMotionsByParty(fromDate?: string, toDate?: string, options?: any) {
        return MotionsApiFp(this.configuration).getMotionsByParty(fromDate, toDate, options)(this.fetch, this.basePath);
    }

}

