AWS_REGION: ${self:provider.region}
ES_SERVER: "elasticsearch:9200"
SQS_URL: "http://sqs:9324/queue/wdip-import-local"
STATUS_INDEX_IPS: "status-ips"
STATUS_INDEX_SQS: "status-sqs"
WDIP_IS_LOCAL_ENV: true
WDIP_MOTION_INDEX: "motions"
