service: wdip-be

app: motioner
tenant: markushont

plugins:
  - serverless-offline-sqs
  - serverless-offline-scheduler
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10
  timeout: 300
  profile: wdip-test
  stage: dev
  region: eu-west-1
  environment: ${file(./environment.yml)}

functions:
  getPendingMotions:
    handler: apiHandler.getPendingMotions
    events:
      - http:
          path: motions/pending
          method: get
  getMotionsByParty:
    handler: apiHandler.getMotionsByParty
    events:
      - http:
          path: motions/byparty
          method: get
  getMotion:
    handler: apiHandler.getMotionById
    events:
      - http:
          path: motions/{id}
          method: get
          requests:
            parameters:
              paths:
                id: true
  getWordCloud:
    handler: apiHandler.getWordCloud
    events:
      - http:
          path: charts/wordcloud
          method: get
  getAllParties:
    handler: apiHandler.getAllParties
    events:
      - http:
          path: partydata/allparties
          method: get
  adminStartImport:
    handler: importHandler.adminStartImport
    events:
      - http:
          path: admin/import
          method: post
          requests:
            parameters:
              querystrings:
                documentType: false
                fromDate: false
                toDate: false
  adminStartUpdateImport:
    handler: importHandler.startUpdateImport
    events:
      - schedule:
          rate: rate(1 day)
          input:
            documentType: mot
      - schedule:
          rate: rate(1 day)
          input:
            documentType: prop
      - http:
          path: admin/import/update
          method: post
          requests:
            parameters:
              querystrings:
                fromDate: false
                documentType: false
  adminHandleImportQueueEvent:
    handler: importHandler.handleImportQueueEvent
    events:
      - sqs:
          arn: arn:aws:sqs:eu-west-1:843375259671:wdip-import
          batchSize: 1
  adminLogQueueStatus:
    handler: importHandler.logQueueStatus
    events:
      - schedule: rate(1 minute)

custom:
  serverless-offline-sqs:
    endpoint: http://sqs:9324
    region: ${self:provider.region}
    accessKeyId: root
    secretAccessKey: root
    skipCacheInvalidation: false
  serverless-offline:
    location: ./dist
