service: wdip-be

app: wdip-be
tenant: hejare

plugins:
  - serverless-plugin-typescript
  - serverless-offline-sqs
  - serverless-offline-scheduler
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10
  profile: wdip-test
  region: eu-west-1
  environment: ${file(./environment_${opt:stage, "local"}.yml)}
  enableScheduledImports: true
  enableScheduledAggregations: true
  iamRoleStatements:
    - Effect: Allow
      Action:
        - es:ESHttpPost
        - es:ESHttpPut
        - es:ESHttpDelete
        - es:ESHttpGet
        - sqs:ReceiveMessage
        - sqs:DeleteMessage
        - sqs:GetQueueAttributes
        - sqs:SendMessage
        - lambda:InvokeFunction
      Resource:
        - arn:aws:es:${self:provider.region}:843375259671:domain/wdip-${opt:stage, "local"}
        - arn:aws:sqs:${self:provider.region}:843375259671:wdip-import-${opt:stage, "local"}
        - arn:aws:lambda:${self:provider.region}:843375259671:*

functions:
  - ${file(./functions/aggregate_functions.yml)}
  - ${file(./functions/web_apis.yml)}
  - ${file(./functions/import_functions.yml)}

custom:
  serverless-offline-sqs:
    endpoint: http://sqs:9324
    region: ${self:provider.region}
    accessKeyId: root
    secretAccessKey: root
    skipCacheInvalidation: false
